distributions:
  - name: my-cloudfront
    aliases:
      - my-cloudfront.nextdrive.io
    department: SRE
    project: EXAMPLE
    bucket_name: my-bucket
    origin_path: ""
    logging_bucket: ""
    logging_prefix: ""
    response_headers_policy: "NoStoreResponseHeader"
    custom_error_response:
      - error_caching_min_ttl: "10"
        error_code: "403"
        response_code: "200"
        response_page_path: "/index.html"
      - error_caching_min_ttl: "10"
        error_code: "404"
        response_code: "200"
        response_page_path: "/index.html"

response_headers_policies:
  - name: "NoStoreResponseHeader"
    custom_headers_configs:
      - header: "Cache-Control"
        override: true
        value: "no-store"
