subnets:
# application
- cidr: 10.2.4.0/24
  name: my-application-ap-northeast-1a
  zone: ap-northeast-1a
- cidr: 10.2.5.0/24
  name: my-application-ap-northeast-1c
  zone: ap-northeast-1c
- cidr: 10.2.6.0/24
  name: my-application-ap-northeast-1d
  zone: ap-northeast-1d
# intra
- cidr: 10.2.8.0/24
  name: my-intra-ap-northeast-1a
  zone: ap-northeast-1a
- cidr: 10.2.9.0/24
  name: my-intra-ap-northeast-1c
  zone: ap-northeast-1c
- cidr: 10.2.10.0/24
  name: my-intra-ap-northeast-1d
  zone: ap-northeast-1d
# public
- cidr: 10.2.0.0/24
  name: my-public-ap-northeast-1a
  zone: ap-northeast-1a
- cidr: 10.2.1.0/24
  name: my-public-ap-northeast-1c
  zone: ap-northeast-1c
- cidr: 10.2.2.0/24
  name: my-public-ap-northeast-1d
  zone: ap-northeast-1d
# persistence
- cidr: 10.2.16.0/24
  name: my-persistence-ap-northeast-1a
  zone: ap-northeast-1a
- cidr: 10.2.17.0/24
  name: my-persistence-ap-northeast-1c
  zone: ap-northeast-1c
- cidr: 10.2.18.0/24
  name: my-persistence-ap-northeast-1d
  zone: ap-northeast-1d
# nat
- cidr: 10.2.3.0/24
  name: my-nat-server
  zone: ap-northeast-1c
