alias:
  - alias_target:
      dns_name: k8s-nginxing-mynginxi-420ab563fa-0e4d90abe2740adb.elb.ap-northeast-1.amazonaws.com.
      evaluate_target_health: false
      hosted_zone_id: Z31USIVHYNEOWT
    name: alias-test
    type: CNAME

simple:
  - name: simple-test
    records:
      - 10.4.3.2
    ttl: 300
    type: A

tags: []

vpcs:
- vpc_id: vpc-049f62a6dc464cb1c
  vpc_region: ap-northeast-1

zone_id: Z04227961BT9BSTA95P7
